interface ZIF_I_RBKEMPTP1_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZI_RBKEMPTP1,
 ACTIVATION                     TYPE /BOBF/ACT_KEY VALUE '128D52C118A61EE9A0D3746DB10F0086',
 CREATE_ZI_RBKEMPTP1            TYPE /BOBF/ACT_KEY VALUE '128D52C118A61EE9A0D3746DB10CA086',
 DELETE_ZI_RBKEMPTP1            TYPE /BOBF/ACT_KEY VALUE '128D52C118A61EE9A0D3746DB10D2086',
 EDIT                           TYPE /BOBF/ACT_KEY VALUE '128D52C118A61EE9A0D3746DB10EE086',
 LOCK_ZI_RBKEMPTP1              TYPE /BOBF/ACT_KEY VALUE '128D52C118A61EE9A0D3746DB10BE086',
 PREPARATION                    TYPE /BOBF/ACT_KEY VALUE '128D52C118A61EE9A0D3746DB10F4086',
 SAVE_ZI_RBKEMPTP1              TYPE /BOBF/ACT_KEY VALUE '128D52C118A61EE9A0D3746DB10DA086',
 UNLOCK_ZI_RBKEMPTP1            TYPE /BOBF/ACT_KEY VALUE '128D52C118A61EE9A0D3746DB10C2086',
 UPDATE_ZI_RBKEMPTP1            TYPE /BOBF/ACT_KEY VALUE '128D52C118A61EE9A0D3746DB10CE086',
 VALIDATE_ZI_RBKEMPTP1          TYPE /BOBF/ACT_KEY VALUE '128D52C118A61EE9A0D3746DB10D6086',
 VALIDATION                     TYPE /BOBF/ACT_KEY VALUE '128D52C118A61EE9A0D3746DB10F2086',
      END OF ZI_RBKEMPTP1,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZI_RBKEMPTP1,
        BEGIN OF EDIT,
 PRESERVE_CHANGES               TYPE STRING VALUE 'PRESERVE_CHANGES',
        END OF EDIT,
        BEGIN OF LOCK_ZI_RBKEMPTP1,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ZI_RBKEMPTP1,
        BEGIN OF PREPARATION,
 SIDEEFFECTSQUALIFIER           TYPE STRING VALUE 'SIDEEFFECTSQUALIFIER',
        END OF PREPARATION,
        BEGIN OF UNLOCK_ZI_RBKEMPTP1,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ZI_RBKEMPTP1,
        BEGIN OF VALIDATION,
 SIDEEFFECTSQUALIFIER           TYPE STRING VALUE 'SIDEEFFECTSQUALIFIER',
        END OF VALIDATION,
      END OF ZI_RBKEMPTP1,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZI_RBKEMPTP1,
 ACTIVE_ENTITY_KEY              TYPE /BOBF/OBM_ALTKEY_KEY VALUE '128D52C118A61EE9A0D3746DB10EC086',
      END OF ZI_RBKEMPTP1,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZI_RBKEMPTP1,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '128D52C118A61EE9A0D3746DB10BC086',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '128D52C118A61EE9A0D3746DB10B8086',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '128D52C118A61EE9A0D3746DB10C8086',
      END OF ZI_RBKEMPTP1,
      BEGIN OF ZI_RBKEMPTP1_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '128D52C118A61EE9A0D3746DB10E0086',
      END OF ZI_RBKEMPTP1_LOCK,
      BEGIN OF ZI_RBKEMPTP1_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '128D52C118A61EE9A0D3746DB10DE086',
      END OF ZI_RBKEMPTP1_MESSAGE,
      BEGIN OF ZI_RBKEMPTP1_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '128D52C118A61EE9A0D3746DB10E2086',
      END OF ZI_RBKEMPTP1_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZI_RBKEMPTP1,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZI_RBKEMPTP1,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '128D52C118A61EE9A0D3746DB10AE086' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZI_RBKEMPTP1' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZI_RBKEMPTP1,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE '128D52C118A61EE9A0D3746DB10F6086',
 CENTRAL_ADMIN_DATA             TYPE /BOBF/DET_KEY VALUE '128D52C118A61EE9A0D3746DB10F8086',
 DRAFT_ACTION_CONTROL           TYPE /BOBF/DET_KEY VALUE '128D52C118A61EE9A0D3746DB1104086',
 DRAFT_SYS_ADMIN_DATA           TYPE /BOBF/DET_KEY VALUE '128D52C118A61EE9A0D3746DB1102086',
 DURABLE_LOCK_CLEANUP_CLEANUP   TYPE /BOBF/DET_KEY VALUE '128D52C118A61EE9A0D3746DB1100086',
 DURABLE_LOCK_CLEANUP_DELETE    TYPE /BOBF/DET_KEY VALUE '128D52C118A61EE9A0D3746DB10FA086',
 DURABLE_LOCK_CLEANUP_FAIL_SAVE TYPE /BOBF/DET_KEY VALUE '128D52C118A61EE9A0D3746DB10FE086',
 DURABLE_LOCK_CLEANUP_SUCC_SAVE TYPE /BOBF/DET_KEY VALUE '128D52C118A61EE9A0D3746DB10FC086',
      END OF ZI_RBKEMPTP1,
    END OF SC_DETERMINATION .
  constants:
    BEGIN OF SC_GROUP,
 DRAFT_CONSISTENCY              TYPE /BOBF/OBM_GROUP_KEY VALUE '128D52C118A61EE9A0D3746DB10E6086',
    END OF SC_GROUP .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZI_RBKEMPTP1                   TYPE /BOBF/OBM_NODE_KEY VALUE '128D52C118A61EE9A0D3746DB10B2086',
 ZI_RBKEMPTP1_LOCK              TYPE /BOBF/OBM_NODE_KEY VALUE '128D52C118A61EE9A0D3746DB10BA086',
 ZI_RBKEMPTP1_MESSAGE           TYPE /BOBF/OBM_NODE_KEY VALUE '128D52C118A61EE9A0D3746DB10B6086',
 ZI_RBKEMPTP1_PROPERTY          TYPE /BOBF/OBM_NODE_KEY VALUE '128D52C118A61EE9A0D3746DB10C6086',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZI_RBKEMPTP1,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  EMP_ID                         TYPE STRING VALUE 'EMP_ID',
  EMP_NAME                       TYPE STRING VALUE 'EMP_NAME',
  EMP_AGE                        TYPE STRING VALUE 'EMP_AGE',
  ACTIVEUUID                     TYPE STRING VALUE 'ACTIVEUUID',
  HASACTIVEENTITY                TYPE STRING VALUE 'HASACTIVEENTITY',
  DRAFTENTITYCREATIONDATETIME    TYPE STRING VALUE 'DRAFTENTITYCREATIONDATETIME',
  DRAFTENTITYLASTCHANGEDATETIME  TYPE STRING VALUE 'DRAFTENTITYLASTCHANGEDATETIME',
  DRAFTENTITYCONSISTENCYSTATUS   TYPE STRING VALUE 'DRAFTENTITYCONSISTENCYSTATUS',
  ISACTIVEENTITY                 TYPE STRING VALUE 'ISACTIVEENTITY',
      END OF ZI_RBKEMPTP1,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZI_RBKEMPTP1,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '128D52C118A61EE9A0D3746DB10B4086',
      END OF ZI_RBKEMPTP1,
    END OF SC_NODE_CATEGORY .
  constants:
    BEGIN OF SC_STATUS_VARIABLE,
      BEGIN OF ZI_RBKEMPTP1,
 DRAFT_CONSISTENCY_STATUS       TYPE /BOBF/STA_VAR_KEY VALUE '128D52C118A61EE9A0D3746DB10E4086',
      END OF ZI_RBKEMPTP1,
    END OF SC_STATUS_VARIABLE .
  constants:
    BEGIN OF SC_VALIDATION,
      BEGIN OF ZI_RBKEMPTP1,
 DURABLE_LOCK_CREATE_FOR_NEW    TYPE /BOBF/VAL_KEY VALUE '128D52C118A61EE9A0D3746DB1106086',
      END OF ZI_RBKEMPTP1,
    END OF SC_VALIDATION .
endinterface.